project_id = "rpehngjvwcnipvkouluu"

[functions.pull-changes]
verify_jwt = false

[functions.push-data]
verify_jwt = false

[functions.report-health]
verify_jwt = false

[functions.upload-backup]
verify_jwt = false
