import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { Receipt, CheckCircle, Plus, X, Trash2, Filter, GlassWater, ExternalLink } from "lucide-react";
import { CardSkeleton, TableSkeleton } from "@/components/LoadingSkeletons";
import { useExpenses, useCreateExpense, useApproveExpense, useDeleteExpense } from "@/hooks/use-casino-data";
import { useActiveShift } from "@/hooks/use-shift";
import { useExpenseAnalytics, type ExpenseStatus, type ExpenseTarget } from "@/hooks/use-expenses-analytics";
import { useAuth } from "@/lib/auth-context";
import { getBusinessDate } from "@/lib/business-day";
import { useEffectiveBusinessDate } from "@/hooks/use-business-day-closure";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NumberInput } from "@/components/ui/number-input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/layout/PageHeader";
import { fmtDateOnly } from "@/lib/format-date";

import { PlayerNameAutocomplete } from "@/components/PlayerNameAutocomplete";
import { formatCurrency } from "@/lib/currency";

// Manual-entry categories (bar_charge / pos_comp are auto-generated by POS).
const CATS = [
  { value: "food", label: "Food" },
  { value: "alcohol", label: "Alcohol" },
  { value: "taxi", label: "Taxi" },
  { value: "hotel", label: "Hotel" },
  { value: "flight", label: "Flight" },
  { value: "other", label: "Other" },
];

// All categories that may appear in history (incl. POS auto-generated).
const ALL_CATS = [
  ...CATS,
  { value: "pos_comp", label: "POS Comp" },
  { value: "bar_charge", label: "Bar charge" },
];

const CAT_COLORS: Record<string, string> = {
  food: "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-400",
  alcohol: "bg-purple-100 text-purple-700 dark:bg-purple-500/15 dark:text-purple-400",
  taxi: "bg-yellow-100 text-yellow-700 dark:bg-yellow-500/15 dark:text-yellow-400",
  hotel: "bg-blue-100 text-blue-700 dark:bg-blue-500/15 dark:text-blue-400",
  flight: "bg-sky-100 text-sky-700 dark:bg-sky-500/15 dark:text-sky-400",
  other: "bg-muted text-muted-foreground",
  pos_comp: "bg-orange-100 text-orange-700 dark:bg-orange-500/15 dark:text-orange-400",
  bar_charge: "bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-400",
};

interface DraftRow {
  uid: string;
  target: "casino" | "player" | "";
  player_name: string;
  category: string;
  amount: string;
  description: string;
}

const newDraft = (): DraftRow => ({
  uid: Math.random().toString(36).slice(2),
  target: "",
  player_name: "",
  category: "",
  amount: "",
  description: "",
});

const Expenses = () => {
  const { isManager } = useAuth();
  const { data: serverBusinessDate } = useEffectiveBusinessDate();
  const businessDate = serverBusinessDate || getBusinessDate();

  // ── Filters ──────────────────────────────────────────────
  const [from, setFrom] = useState<string>(businessDate);
  const [to, setTo] = useState<string>(businessDate);
  const [category, setCategory] = useState<string>("all");
  const [target, setTarget] = useState<ExpenseTarget>("all");
  const [status, setStatus] = useState<ExpenseStatus>("all");
  const [search, setSearch] = useState<string>("");
  const [showBarDetails, setShowBarDetails] = useState<boolean>(false);

  const isSingleDay = from === to;
  const { data: shift } = useActiveShift();
  const { data: expenses = [], isLoading: loadingExpenses } = useExpenses(
    isSingleDay ? from : undefined,
    "live_game",
    isSingleDay ? undefined : { from, to },
  );
  const create = useCreateExpense();
  const approve = useApproveExpense();
  const del = useDeleteExpense();
  const [drafts, setDrafts] = useState<DraftRow[]>([newDraft()]);

  const isLoading = loadingExpenses;

  const filters = useMemo(
    () => ({
      categories: category === "all" ? undefined : [category],
      target,
      status,
      search,
    }),
    [category, target, status, search],
  );
  const analytics = useExpenseAnalytics(expenses as any, filters);

  const resetFilters = () => {
    setFrom(businessDate);
    setTo(businessDate);
    setCategory("all");
    setTarget("all");
    setStatus("all");
    setSearch("");
  };

  const updateDraft = (uid: string, patch: Partial<DraftRow>) =>
    setDrafts((d) => d.map((r) => (r.uid === uid ? { ...r, ...patch } : r)));

  const removeDraft = (uid: string) =>
    setDrafts((d) => (d.length > 1 ? d.filter((r) => r.uid !== uid) : d));

  const submitDraft = async (uid: string) => {
    const row = drafts.find((r) => r.uid === uid);
    if (!row) return;
    if (!row.target) return toast.error("Choose target");
    if (row.target === "player" && !row.player_name.trim()) return toast.error("Enter player name");
    if (!row.category) return toast.error("Choose category");
    const amt = Number(row.amount);
    if (!amt || amt <= 0) return toast.error("Amount must be > 0");
    if (!shift?.id) return toast.error("No active shift");
    try {
      await new Promise<void>((resolve, reject) => {
        create.mutate(
          {
            category: row.category,
            amount: amt,
            description: row.description,
            player_id: null,
            player_name: row.target === "player" ? row.player_name.trim() : "",
            shift_id: shift.id,
          },
          { onSuccess: () => resolve(), onError: (e: any) => reject(e) },
        );
      });
      setDrafts((d) => [...d.filter((r) => r.uid !== uid), newDraft()]);
    } catch {
      /* toast handled */
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <PageHeader icon={Receipt} title="Expenses" subtitle="Loading…" />
        <CardSkeleton count={3} />
        <TableSkeleton rows={5} cols={6} />
      </div>
    );
  }

  const labelForCat = (c: string) => ALL_CATS.find((x) => x.value === c)?.label || c;

  return (
    <div>
      <PageHeader
        icon={Receipt}
        title="Expenses"
        subtitle={`Immutable · ${analytics.filtered.length} of ${expenses.length} records · ${analytics.pendingCount} pending`}
        date
      />

      {/* KPI cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
        <div className="cms-panel p-3">
          <p className="text-[10px] uppercase text-muted-foreground tracking-wider">Total</p>
          <p className="font-mono text-lg font-bold text-card-foreground">{formatCurrency(analytics.totalAmount)}</p>
        </div>
        <div className="cms-panel p-3">
          <p className="text-[10px] uppercase text-muted-foreground tracking-wider">Approved</p>
          <p className="font-mono text-lg font-bold cms-amount-positive">{formatCurrency(analytics.approvedAmount)}</p>
        </div>
        <div className="cms-panel p-3">
          <p className="text-[10px] uppercase text-muted-foreground tracking-wider">Pending</p>
          <p className="font-mono text-lg font-bold text-accent">{analytics.pendingCount}</p>
        </div>
        <button
          type="button"
          onClick={() => setShowBarDetails((v) => !v)}
          className="cms-panel p-3 text-left transition hover:bg-muted/40"
          title="Toggle bar charge details"
        >
          <p className="text-[10px] uppercase text-muted-foreground tracking-wider flex items-center gap-1">
            <GlassWater className="w-3 h-3" /> Bar charges
          </p>
          <p className="font-mono text-lg font-bold text-card-foreground">
            {formatCurrency(analytics.barChargeTotal)}
            <span className="ml-2 text-xs text-muted-foreground font-normal">· {analytics.barChargeCount}</span>
          </p>
        </button>
      </div>

      {/* Filters */}
      <div className="cms-panel p-3 mb-4">
        <div className="flex items-center gap-2 mb-2">
          <Filter className="w-3.5 h-3.5 text-muted-foreground" />
          <h3 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">Filters</h3>
          <Button variant="ghost" size="sm" className="h-7 text-xs ml-auto" onClick={resetFilters}>
            Reset
          </Button>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-6 gap-2">
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">From</label>
            <Input type="date" value={from} max={to} onChange={(e) => setFrom(e.target.value)} className="h-8 text-xs" />
          </div>
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">To</label>
            <Input type="date" value={to} min={from} onChange={(e) => setTo(e.target.value)} className="h-8 text-xs" />
          </div>
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">Category</label>
            <Select value={category} onValueChange={setCategory}>
              <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All categories</SelectItem>
                {ALL_CATS.map((c) => (
                  <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">Target</label>
            <Select value={target} onValueChange={(v) => setTarget(v as ExpenseTarget)}>
              <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All targets</SelectItem>
                <SelectItem value="casino">Casino</SelectItem>
                <SelectItem value="player">Player</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">Status</label>
            <Select value={status} onValueChange={(v) => setStatus(v as ExpenseStatus)}>
              <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All statuses</SelectItem>
                <SelectItem value="approved">Approved</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="text-[10px] uppercase text-muted-foreground">Search</label>
            <Input
              placeholder="Player or description…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="h-8 text-xs"
            />
          </div>
        </div>
      </div>

      {/* Bar charges details (toggle) */}
      {showBarDetails && (
        <div className="cms-panel overflow-hidden mb-4">
          <div className="px-4 py-2 border-b border-border flex items-center justify-between">
            <h3 className="text-sm font-semibold text-card-foreground flex items-center gap-2">
              <GlassWater className="w-4 h-4 text-amber-500" /> Bar charges · by player
            </h3>
            <span className="text-[10px] text-muted-foreground">
              Auto-generated from POS · linked to player tab
            </span>
          </div>
          {analytics.barChargesByPlayer.length === 0 ? (
            <p className="text-center text-muted-foreground text-sm py-6">No bar charges in this period</p>
          ) : (
            <table className="w-full">
              <thead>
                <tr className="border-b border-border text-[10px] uppercase tracking-wider text-muted-foreground">
                  <th className="text-left px-3 py-2">Player</th>
                  <th className="text-center px-3 py-2">Charges</th>
                  <th className="text-right px-3 py-2">Total</th>
                  <th className="text-left px-3 py-2">Last charge</th>
                  <th className="text-center px-3 py-2 w-[80px]"></th>
                </tr>
              </thead>
              <tbody>
                {analytics.barChargesByPlayer.map((p) => (
                  <tr key={`${p.player_id}-${p.name}`} className="border-b border-border last:border-0">
                    <td className="px-3 py-2 text-sm">{p.name}</td>
                    <td className="px-3 py-2 text-center font-mono text-xs">{p.count}</td>
                    <td className="px-3 py-2 text-right font-mono text-sm cms-amount-negative">
                      {formatCurrency(p.total)}
                    </td>
                    <td className="px-3 py-2 text-xs text-muted-foreground font-mono">
                      {fmtDateOnly(p.last_at)}
                      {" · "}
                      {new Date(p.last_at).toLocaleTimeString("en-GB", {
                        timeZone: "Africa/Dar_es_Salaam",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="px-3 py-2 text-center">
                      {p.player_id && (
                        <Link
                          to={`/players/${p.player_id}`}
                          className="inline-flex items-center justify-center h-7 w-7 rounded hover:bg-muted text-muted-foreground hover:text-foreground"
                          title="Open player profile"
                        >
                          <ExternalLink className="w-3.5 h-3.5" />
                        </Link>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* Entry table — every OK adds a fresh row */}
      <div className="cms-panel overflow-visible mb-6">
        <div className="px-4 py-2 border-b border-border flex items-center justify-between">
          <h3 className="text-sm font-semibold text-card-foreground">New entries</h3>
          <Button size="sm" variant="outline" onClick={() => setDrafts((d) => [...d, newDraft()])} className="h-8 gap-1.5">
            <Plus className="w-3.5 h-3.5" /> Row
          </Button>
        </div>
        <table className="w-full">
          <thead>
            <tr className="border-b border-border text-[10px] uppercase tracking-wider text-muted-foreground">
              <th className="text-left px-3 py-2">Target</th>
              <th className="text-left px-3 py-2">Player</th>
              <th className="text-left px-3 py-2">Category</th>
              <th className="text-right px-3 py-2">Amount (TZS)</th>
              <th className="text-left px-3 py-2">Description</th>
              <th className="text-center px-3 py-2 w-[140px]">Action</th>
            </tr>
          </thead>
          <tbody>
            {drafts.map((d) => (
              <tr key={d.uid} className="border-b border-border last:border-0">
                <td className="px-2 py-1.5">
                  <Select
                    value={d.target}
                    onValueChange={(v) => updateDraft(d.uid, { target: v as "casino" | "player", player_name: "" })}
                  >
                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Target" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="casino">Casino</SelectItem>
                      <SelectItem value="player">Player</SelectItem>
                    </SelectContent>
                  </Select>
                </td>
                <td className="px-2 py-1.5">
                  <PlayerNameAutocomplete
                    placeholder={d.target === "player" ? "Player name" : "—"}
                    value={d.player_name}
                    onChange={(v) => updateDraft(d.uid, { player_name: v })}
                    disabled={d.target !== "player"}
                  />
                </td>
                <td className="px-2 py-1.5">
                  <Select value={d.category} onValueChange={(v) => updateDraft(d.uid, { category: v })}>
                    <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Category" /></SelectTrigger>
                    <SelectContent>
                      {CATS.map((c) => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </td>
                <td className="px-2 py-1.5">
                  <NumberInput placeholder="0" value={d.amount} onChange={(v) => updateDraft(d.uid, { amount: v })} className="h-8 text-xs text-right" />
                </td>
                <td className="px-2 py-1.5">
                  <Input placeholder="Description" value={d.description} onChange={(e) => updateDraft(d.uid, { description: e.target.value })} className="h-8 text-xs" />
                </td>
                <td className="px-2 py-1.5 text-center">
                  <div className="inline-flex gap-1">
                    <Button size="sm" className="h-8 px-3" onClick={() => submitDraft(d.uid)} disabled={create.isPending}>
                      OK
                    </Button>
                    {drafts.length > 1 && (
                      <Button size="sm" variant="ghost" className="h-8 w-8 p-0" onClick={() => removeDraft(d.uid)}>
                        <X className="w-3.5 h-3.5" />
                      </Button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* History */}
      <div className="cms-panel overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-border text-[10px] uppercase tracking-wider text-muted-foreground">
              <th className="text-left px-3 py-2">Date</th>
              <th className="text-left px-3 py-2">Time</th>
              <th className="text-left px-3 py-2">Category</th>
              <th className="text-left px-3 py-2">Target / Player</th>
              <th className="text-right px-3 py-2">Amount</th>
              <th className="text-left px-3 py-2">Description</th>
              <th className="text-center px-3 py-2">Status</th>
              <th className="text-center px-3 py-2">Action</th>
            </tr>
          </thead>
          <tbody>
            {analytics.filtered.length === 0 ? (
              <tr><td colSpan={8} className="text-center text-muted-foreground text-sm py-8">No expenses match the filters</td></tr>
            ) : analytics.filtered.map((exp: any) => {
              const playerName = exp.players
                ? `${exp.players.first_name} ${exp.players.last_name}`
                : exp.player_name || "Casino";
              return (
                <tr key={exp.id} className="border-b border-border last:border-0">
                  <td className="px-3 py-2 text-xs font-mono text-muted-foreground">
                    {fmtDateOnly(exp.created_at)}
                  </td>
                  <td className="px-3 py-2 text-xs font-mono text-muted-foreground">
                    {new Date(exp.created_at).toLocaleTimeString("en-GB", { timeZone: "Africa/Dar_es_Salaam", hour: "2-digit", minute: "2-digit" })}
                  </td>
                  <td className="px-3 py-2">
                    <span className={`text-[10px] font-mono uppercase px-1.5 py-0.5 rounded ${CAT_COLORS[exp.category] || CAT_COLORS.other}`}>
                      {labelForCat(exp.category)}
                    </span>
                  </td>
                  <td className="px-3 py-2 text-sm">
                    {exp.player_id ? (
                      <Link
                        to={`/players/${exp.player_id}`}
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        {playerName}
                        <ExternalLink className="w-3 h-3 opacity-60" />
                      </Link>
                    ) : (
                      <span className="text-muted-foreground">{playerName}</span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-right font-mono text-sm cms-amount-negative">
                    {formatCurrency(Number(exp.amount))}
                  </td>
                  <td className="px-3 py-2 text-xs text-muted-foreground">{exp.description || "—"}</td>
                  <td className="px-3 py-2 text-center">
                    {exp.approved ? (
                      <span className="cms-status-active text-xs"><CheckCircle className="w-3 h-3 inline mr-0.5" /> Approved</span>
                    ) : (
                      <Badge variant="secondary" className="text-[10px]">Pending</Badge>
                    )}
                  </td>
                  <td className="px-3 py-2 text-center">
                    <div className="inline-flex gap-1">
                      {!exp.approved && isManager && (
                        <Button variant="outline" size="sm" className="text-xs h-7" onClick={() => approve.mutate(exp.id)} disabled={approve.isPending}>Approve</Button>
                      )}
                      {!exp.approved && exp.category !== "bar_charge" && (
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 w-7 p-0 text-destructive hover:text-destructive hover:bg-destructive/10"
                          onClick={() => del.mutate({ id: exp.id, amount: Number(exp.amount), category: exp.category })}
                          title="Cancel expense"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Expenses;
