ALTER TABLE public.casinos 
  ADD COLUMN IF NOT EXISTS shift_start text NOT NULL DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS shift_end text NOT NULL DEFAULT '05:00',
  ADD COLUMN IF NOT EXISTS tables_open text NOT NULL DEFAULT '17:30',
  ADD COLUMN IF NOT EXISTS breaklist_lock text NOT NULL DEFAULT '05:30';